"""Build the measurement grid from what Deriv actually offers.

The grid is discovered, never hardcoded. Symbol codes, available contract
types and permitted duration bounds all change, and a census that assumes them
would silently measure nothing. Discovery also enforces the study's scope
decision: synthetic and broker-created instruments are excluded, because their
statistics say nothing about a real-market strategy -- their price process is
generated by the counterparty.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from typing import Any, Awaitable, Callable

from .config import GridConfig
from . import protocol
from .protocol import (ACTIVE_SYMBOLS_VARIANTS, CONTRACT_TYPES,
                       CONTRACTS_FOR_VARIANTS, ContractOffering, DerivError,
                       SymbolInfo, duration_to_seconds, parse_active_symbols,
                       parse_contracts_for)

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class Cell:
    """One measurable combination: what to quote, and how often."""

    symbol: str
    display_name: str
    contract_type: str
    variant: str
    direction: str
    duration_seconds: int
    pip: float | None

    @property
    def key(self) -> str:
        return f"{self.symbol}|{self.contract_type}|{self.duration_seconds}"

    @property
    def duration_request(self) -> tuple[int, str]:
        """Express the duration in the largest exact unit Deriv accepts."""
        if self.duration_seconds % 60 == 0:
            return self.duration_seconds // 60, "m"
        return self.duration_seconds, "s"


@dataclass(frozen=True)
class SymbolProbe:
    """Outcome of one attempt at an ``active_symbols`` request shape."""

    variant: str
    request: dict[str, Any]
    count: int
    error: str | None = None

    @property
    def worked(self) -> bool:
        return self.error is None and self.count > 0


async def resolve_active_symbols(
    send: Callable[[dict[str, Any]], Awaitable[dict[str, Any]]],
) -> tuple[list[SymbolInfo], list[SymbolProbe]]:
    """Find a request shape that actually returns instruments.

    Tries each known variant in turn and stops at the first that returns a
    non-empty list. Returns the symbols alongside the full attempt log, so a
    total failure reports which shapes were tried and what each one said
    rather than a bare zero.
    """
    probes: list[SymbolProbe] = []
    for variant, request in ACTIVE_SYMBOLS_VARIANTS:
        try:
            payload = await send(dict(request))
        except DerivError as exc:
            probes.append(SymbolProbe(variant, request, 0, str(exc)))
            continue
        except Exception as exc:  # noqa: BLE001 - a bad variant must not abort
            probes.append(SymbolProbe(variant, request, 0, repr(exc)))
            continue
        symbols = parse_active_symbols(payload)
        probes.append(SymbolProbe(variant, request, len(symbols)))
        if symbols:
            log.info("active_symbols variant %r returned %d symbols",
                     variant, len(symbols))
            return symbols, probes
    log.error("no active_symbols variant returned instruments; tried %s",
              [p.variant for p in probes])
    return [], probes


async def resolve_contracts_for(
    send: Callable[[dict[str, Any]], Awaitable[dict[str, Any]]],
    symbol: str,
    currency: str = "USD",
) -> tuple[list[ContractOffering], list[SymbolProbe]]:
    """Fetch a symbol's offerings, trying each request shape until one works."""
    probes: list[SymbolProbe] = []
    for variant, product_type in CONTRACTS_FOR_VARIANTS:
        request = protocol.contracts_for(symbol, currency, product_type)
        try:
            payload = await send(dict(request))
        except DerivError as exc:
            probes.append(SymbolProbe(variant, request, 0, str(exc)))
            continue
        except Exception as exc:  # noqa: BLE001
            probes.append(SymbolProbe(variant, request, 0, repr(exc)))
            continue
        offerings = parse_contracts_for(payload)
        probes.append(SymbolProbe(variant, request, len(offerings)))
        if offerings:
            return offerings, probes
    return [], probes


def is_excluded(symbol: SymbolInfo, patterns: list[str]) -> bool:
    """Match exclusion patterns against every field that could reveal a
    synthetic instrument. Deriv names them inconsistently across the symbol
    code, the display name and the submarket, so all three are checked."""
    haystack = " ".join([symbol.symbol, symbol.display_name,
                         symbol.submarket, symbol.market]).lower()
    return any(pattern.lower() in haystack for pattern in patterns)


def select_symbols(symbols: list[SymbolInfo], grid: GridConfig) -> list[SymbolInfo]:
    """Apply market filter, exclusion patterns and the explicit allow-list.

    Symbols whose exchange is currently closed are retained: over fourteen days
    they will open, and dropping them here would bias the census toward
    whichever session happened to be live at start-up. The sampler skips them
    while closed.
    """
    allow = {s.upper() for s in grid.symbols}
    chosen: list[SymbolInfo] = []
    for sym in symbols:
        if allow:
            if sym.symbol.upper() not in allow:
                continue
        else:
            if grid.markets and sym.market not in grid.markets:
                continue
            if is_excluded(sym, grid.exclude_patterns):
                continue
        chosen.append(sym)
    return chosen


def offered_contract_types(offerings: list[ContractOffering]) -> set[str]:
    return {o.contract_type for o in offerings if o.contract_type}


def duration_supported(offerings: list[ContractOffering], contract_type: str,
                       seconds: int) -> bool:
    """Whether a duration falls inside the offered bounds for a contract type.

    Offerings with tick-denominated or unparseable bounds are treated as
    permissive: a wrongly included cell costs one rejected proposal and is
    dropped permanently, whereas a wrongly excluded cell is a silent hole in
    the data that only shows up at analysis time.
    """
    relevant = [o for o in offerings if o.contract_type == contract_type]
    if not relevant:
        return False
    for offering in relevant:
        lo = duration_to_seconds(offering.min_duration)
        hi = duration_to_seconds(offering.max_duration)
        if lo is not None and seconds < lo:
            continue
        if hi is not None and seconds > hi:
            continue
        return True
    return False


def build_cells(symbol: SymbolInfo, offerings: list[ContractOffering],
                grid: GridConfig) -> list[Cell]:
    available = offered_contract_types(offerings)
    cells: list[Cell] = []
    for variant in grid.variants:
        rise, fall = CONTRACT_TYPES[variant]
        for direction in grid.directions:
            contract_type = rise if direction == "rise" else fall
            if contract_type not in available:
                log.debug("%s does not offer %s", symbol.symbol, contract_type)
                continue
            for seconds in grid.durations_seconds:
                if not duration_supported(offerings, contract_type, seconds):
                    log.debug("%s %s does not support %ds",
                              symbol.symbol, contract_type, seconds)
                    continue
                cells.append(Cell(
                    symbol=symbol.symbol,
                    display_name=symbol.display_name,
                    contract_type=contract_type,
                    variant=variant,
                    direction=direction,
                    duration_seconds=seconds,
                    pip=symbol.pip,
                ))
    return cells


def summarise(cells: list[Cell]) -> dict[str, int]:
    return {
        "cells": len(cells),
        "symbols": len({c.symbol for c in cells}),
        "contract_types": len({c.contract_type for c in cells}),
        "durations": len({c.duration_seconds for c in cells}),
    }
